export const FETCH_CITIES = 'DATA/CITIES/FETCH_CITIES'
export const SET_CITIES_FETCHING = 'DATA/CITIES/SET_CITIES_FETCHING'
export const SET_CITIES_FETCHING_ERROR = 'DATA/CITIES/SET_CITIES_FETCHING_ERROR'

export const ADD_CITY = 'DATA/CITIES/ADD_CITY'
export const SET_CITY_ADDING = 'DATA/CITIES/SET_CITY_ADDING'
export const SET_CITY_ADDING_ERROR = 'DATA/CITIES/SET_CITY_ADDING_ERROR'

export const REMOVE_CITY = 'DATA/CITIES/REMOVE_CITY'
export const SET_CITY_REMOVING = 'DATA/CITIES/SET_CITY_REMOVING'
export const SET_CITY_REMOVING_ERROR = 'DATA/CITIES/SET_CITY_REMOVING_ERROR'

export const MODIFY_CITY = 'DATA/CITIES/MODIFY_CITY'
export const SET_CITY_MODIFYING = 'DATA/CITIES/SET_CITY_MODIFYING_REMOVING'
export const SET_CITY_MODIFYING_ERROR = 'DATA/CITIES/SET_CITY_MODIFYING_ERROR'