export const FETCH_COACHES = 'DATA/COACHES/FETCH_COACHES'
export const SET_COACHES_FETCHING = 'DATA/COACHES/SET_COACHES_FETCHING'
export const SET_COACHES_FETCHING_ERROR = 'DATA/COACHES/SET_COACHES_FETCHING_ERROR'

export const ADD_COACH = 'DATA/COACHES/ADD_COACH'
export const SET_COACH_ADDING = 'DATA/COACHES/SET_COACH_ADDING'
export const SET_COACH_ADDING_ERROR = 'DATA/COACHES/SET_COACH_ADDING_ERROR'

export const REMOVE_COACH = 'DATA/COACHES/REMOVE_COACH'
export const SET_COACH_REMOVING = 'DATA/COACHES/SET_COACH_REMOVING'
export const SET_COACH_REMOVING_ERROR = 'DATA/COACHES/SET_COACH_REMOVING_ERROR'

export const MODIFY_COACH = 'DATA/COACHES/MODIFY_COACH'
export const SET_COACH_MODIFYING = 'DATA/COACHES/SET_COACH_MODIFYING_REMOVING'
export const SET_COACH_MODIFYING_ERROR = 'DATA/COACHES/SET_COACH_MODIFYING_ERROR'