export const FETCH_GROUPS = 'DATA/GROUPS/FETCH_GROUPS'
export const SET_GROUPS_FETCHING = 'DATA/GROUPS/SET_GROUPS_FETCHING'
export const SET_GROUPS_FETCHING_ERROR = 'DATA/GROUPS/SET_GROUPS_FETCHING_ERROR'

export const ADD_GROUP = 'DATA/GROUPS/ADD_GROUP'
export const SET_GROUP_ADDING = 'DATA/GROUPS/SET_GROUP_ADDING'
export const SET_GROUP_ADDING_ERROR = 'DATA/GROUPS/SET_GROUP_ADDING_ERROR'

export const REMOVE_GROUP = 'DATA/GROUPS/REMOVE_GROUP'
export const SET_GROUP_REMOVING = 'DATA/GROUPS/SET_GROUP_REMOVING'
export const SET_GROUP_REMOVING_ERROR = 'DATA/GROUPS/SET_GROUP_REMOVING_ERROR'

export const MODIFY_GROUP = 'DATA/GROUPS/MODIFY_GROUP'
export const SET_GROUP_MODIFYING = 'DATA/GROUPS/SET_GROUP_MODIFYING_REMOVING'
export const SET_GROUP_MODIFYING_ERROR = 'DATA/GROUPS/SET_GROUP_MODIFYING_ERROR'