export const FETCH_NEWS = 'DATA/NEWS/FETCH_NEWS'
export const SET_NEWS_FETCHING = 'DATA/NEWS/SET_NEWS_FETCHING'
export const SET_NEWS_FETCHING_ERROR = 'DATA/NEWS/SET_NEWS_FETCHING_ERROR'

export const ADD_NEWS = 'DATA/NEWS/ADD_NEWS'
export const SET_NEWS_ADDING = 'DATA/NEWS/SET_NEWS_ADDING'
export const SET_NEWS_ADDING_ERROR = 'DATA/NEWS/SET_NEWS_ADDING_ERROR'

export const REMOVE_NEWS = 'DATA/NEWS/REMOVE_NEWS'
export const SET_NEWS_REMOVING = 'DATA/NEWS/SET_NEWS_REMOVING'
export const SET_NEWS_REMOVING_ERROR = 'DATA/NEWS/SET_NEWS_REMOVING_ERROR'

export const MODIFY_NEWS = 'DATA/NEWS/MODIFY_NEWS'
export const SET_NEWS_MODIFYING = 'DATA/NEWS/SET_NEWS_MODIFYING_REMOVING'
export const SET_NEWS_MODIFYING_ERROR = 'DATA/NEWS/SET_NEWS_MODIFYING_ERROR'