export const FETCH_SCHOOLS = 'DATA/SCHOOLS/FETCH_SCHOOLS'
export const SET_SCHOOLS_FETCHING = 'DATA/SCHOOLS/SET_SCHOOLS_FETCHING'
export const SET_SCHOOLS_FETCHING_ERROR = 'DATA/SCHOOLS/SET_SCHOOLS_FETCHING_ERROR'

export const ADD_SCHOOL = 'DATA/SCHOOLS/ADD_SCHOOL'
export const SET_SCHOOL_ADDING = 'DATA/SCHOOLS/SET_SCHOOL_ADDING'
export const SET_SCHOOL_ADDING_ERROR = 'DATA/SCHOOLS/SET_SCHOOL_ADDING_ERROR'

export const REMOVE_SCHOOL = 'DATA/SCHOOLS/REMOVE_SCHOOL'
export const SET_SCHOOL_REMOVING = 'DATA/SCHOOLS/SET_SCHOOL_REMOVING'
export const SET_SCHOOL_REMOVING_ERROR = 'DATA/SCHOOLS/SET_SCHOOL_REMOVING_ERROR'

export const MODIFY_SCHOOL = 'DATA/SCHOOLS/MODIFY_SCHOOL'
export const SET_SCHOOL_MODIFYING = 'DATA/SCHOOLS/SET_SCHOOL_MODIFYING_REMOVING'
export const SET_SCHOOL_MODIFYING_ERROR = 'DATA/SCHOOLS/SET_SCHOOL_MODIFYING_ERROR'