export const FETCH_STATISTICS = 'DATA/STATISTICS/FETCH_STATISTICS'
export const SET_STATISTICS_FETCHING = 'DATA/STATISTICS/SET_STATISTICS_FETCHING'
export const SET_STATISTICS_FETCHING_ERROR = 'DATA/STATISTICS/SET_STATISTICS_FETCHING_ERROR'

export const ADD_STATISTICS = 'DATA/STATISTICS/ADD_STATISTICS'
export const SET_STATISTICS_ADDING = 'DATA/STATISTICS/SET_STATISTICS_ADDING'
export const SET_STATISTICS_ADDING_ERROR = 'DATA/STATISTICS/SET_STATISTICS_ADDING_ERROR'

export const REMOVE_STATISTICS = 'DATA/STATISTICS/REMOVE_STATISTICS'
export const SET_STATISTICS_REMOVING = 'DATA/STATISTICS/SET_STATISTICS_REMOVING'
export const SET_STATISTICS_REMOVING_ERROR = 'DATA/STATISTICS/SET_STATISTICS_REMOVING_ERROR'

export const MODIFY_STATISTICS = 'DATA/STATISTICS/MODIFY_STATISTICS'
export const SET_STATISTICS_MODIFYING = 'DATA/STATISTICS/SET_STATISTICS_MODIFYING_REMOVING'
export const SET_STATISTICS_MODIFYING_ERROR = 'DATA/STATISTICS/SET_STATISTICS_MODIFYING_ERROR'