export const FETCH_STUDENTS = 'DATA/STUDENTS/FETCH_STUDENTS'
export const SET_STUDENTS_FETCHING = 'DATA/STUDENTS/SET_STUDENTS_FETCHING'
export const SET_STUDENTS_FETCHING_ERROR = 'DATA/STUDENTS/SET_STUDENTS_FETCHING_ERROR'

export const ADD_STUDENT = 'DATA/STUDENTS/ADD_STUDENT'
export const SET_STUDENT_ADDING = 'DATA/STUDENTS/SET_STUDENT_ADDING'
export const SET_STUDENT_ADDING_ERROR = 'DATA/STUDENTS/SET_STUDENT_ADDING_ERROR'

export const REMOVE_STUDENT = 'DATA/STUDENTS/REMOVE_STUDENT'
export const SET_STUDENT_REMOVING = 'DATA/STUDENTS/SET_STUDENT_REMOVING'
export const SET_STUDENT_REMOVING_ERROR = 'DATA/STUDENTS/SET_STUDENT_REMOVING_ERROR'

export const MODIFY_STUDENT = 'DATA/STUDENTS/MODIFY_STUDENT'
export const SET_STUDENT_MODIFYING = 'DATA/STUDENTS/SET_STUDENT_MODIFYING_REMOVING'
export const SET_STUDENT_MODIFYING_ERROR = 'DATA/STUDENTS/SET_STUDENT_MODIFYING_ERROR'