export const FETCH_TOURNAMENTS = 'DATA/TOURNAMENTS/FETCH_TOURNAMENTS'
export const SET_TOURNAMENTS_FETCHING = 'DATA/TOURNAMENTS/SET_TOURNAMENTS_FETCHING'
export const SET_TOURNAMENTS_FETCHING_ERROR = 'DATA/TOURNAMENTS/SET_TOURNAMENTS_FETCHING_ERROR'

export const ADD_TOURNAMENT = 'DATA/TOURNAMENTS/ADD_TOURNAMENT'
export const SET_TOURNAMENT_ADDING = 'DATA/TOURNAMENTS/SET_TOURNAMENT_ADDING'
export const SET_TOURNAMENT_ADDING_ERROR = 'DATA/TOURNAMENTS/SET_TOURNAMENT_ADDING_ERROR'

export const REMOVE_TOURNAMENT = 'DATA/TOURNAMENTS/REMOVE_TOURNAMENT'
export const SET_TOURNAMENT_REMOVING = 'DATA/TOURNAMENTS/SET_TOURNAMENT_REMOVING'
export const SET_TOURNAMENT_REMOVING_ERROR = 'DATA/TOURNAMENTS/SET_TOURNAMENT_REMOVING_ERROR'

export const MODIFY_TOURNAMENT = 'DATA/TOURNAMENTS/MODIFY_TOURNAMENT'
export const SET_TOURNAMENT_MODIFYING = 'DATA/TOURNAMENTS/SET_TOURNAMENT_MODIFYING_REMOVING'
export const SET_TOURNAMENT_MODIFYING_ERROR = 'DATA/TOURNAMENTS/SET_TOURNAMENT_MODIFYING_ERROR'