export const FETCH_USERS = 'DATA/USERS/FETCH_USERS'
export const SET_USERS_FETCHING = 'DATA/USERS/SET_USERS_FETCHING'
export const SET_USERS_FETCHING_ERROR = 'DATA/USERS/SET_USERS_FETCHING_ERROR'

export const ADD_USER = 'DATA/USERS/ADD_USER'
export const SET_USER_ADDING = 'DATA/USERS/SET_USER_ADDING'
export const SET_USER_ADDING_ERROR = 'DATA/USERS/SET_USER_ADDING_ERROR'

export const REMOVE_USER = 'DATA/USERS/REMOVE_USER'
export const SET_USER_REMOVING = 'DATA/USERS/SET_USER_REMOVING'
export const SET_USER_REMOVING_ERROR = 'DATA/USERS/SET_USER_REMOVING_ERROR'

export const MODIFY_USER = 'DATA/USERS/MODIFY_USER'
export const SET_USER_MODIFYING = 'DATA/USERS/SET_USER_MODIFYING_REMOVING'
export const SET_USER_MODIFYING_ERROR = 'DATA/USERS/SET_USER_MODIFYING_ERROR'